loot:
  drop:
    items:
    - STONE:55.0
    - DIRT:60.0
    - COBBLESTONE:50.0
    - GOLD_ORE:10.0
    - IRON_ORE:12.0
    - COAL_ORE:30.0
    - DIAMOND_ORE:5.0
    - MONSTER_EGGS:2.0
    - IRON_AXE:10.0
    - APPLE:30.0
    - BOW:10.0
    - ARROW:30.0
    - COAL:100.0
    - DIAMOND:2.0
    - IRON_INGOT:5.0
    - GOLD_INGOT:5.0
    - IRON_SWORD:10.0
    - WOOD_SWORD:50.0
    - WOOD_PICKAXE:50.0
    - WOOD_AXE:50.0
    - STONE_SWORD:40.0
    - STONE_PICKAXE:40.0
    - STONE_AXE:40.0
    - DIAMOND_SWORD:2.0
    - DIAMOND_PICKAXE:2.0
    - DIAMOND_AXE:2.0
    - STICK:80.0
    - GOLD_SWORD:15.0
    - GOLD_PICKAXE:15.0
    - GOLD_AXE:15.0
    - WOOD_HOE:50.0
    - STONE_HOE:40.0
    - IRON_HOE:100.0
    - DIAMOND_HOE:2.0
    - GOLD_HOE:15.0
    - LEATHER_HELMET:60.0
    - LEATHER_CHESTPLATE:60.0
    - LEATHER_LEGGINGS:60.0
    - LEATHER_BOOTS:60.0
    - CHAINMAIL_HELMET:45.0
    - CHAINMAIL_CHESTPLATE:45.0
    - CHAINMAIL_LEGGINGS:45.0
    - CHAINMAIL_BOOTS:45.0
    - IRON_HELMET:30.0
    - IRON_CHESTPLATE:30.0
    - IRON_LEGGINGS:30.0
    - IRON_BOOTS:30.0
    - DIAMOND_HELMET:2.0
    - DIAMOND_CHESTPLATE:2.0
    - DIAMOND_LEGGINGS:2.0
    - DIAMOND_BOOTS:2.0
    - GOLD_HELMET:10.0
    - GOLD_CHESTPLATE:10.0
    - GOLD_LEGGINGS:10.0
    - GOLD_BOOTS:10.0
    - GOLDEN_APPLE:20.0
    - EGG:50.0
    - RAW_FISH:60.0
    - COOKIE:20.0
