name: TheLoot
main: com.jabstruse.mcloot.loot.Loot
version: 1.0.0
author: HexPang
commands:
   basic:
      description: This is a demo command.
      usage: /<command> [player]
      permission: <plugin name>.basic
      permission-message: You don't have <permission>